### PR TITLE
[FEATURE] Add TCA option to restrict available providers

### PR DESCRIPTION
**Pull request by xperseguers**
Resolves: #10

### CODE REVIEW

**Comment by xperseguers** [comment]
Hope I thought about everything

**Comment by xperseguers** [comment]
Known limitation: won't work properly if you have multiple "icon" fields with various restrictions within the same record

**Comment by xperseguers** [comment]
Mmmh: forgot about `\Blueways\BwIcons\Controller\IconSelectionController::stylesheetsAction()`

**Review by maikschneider — APPROVED** [review]
Looks good & works great!

**Pull request merged**
